name: PR from Version
run-name: PR ${{ inputs.head }} -> ${{ inputs.base }}

inputs:
  version-from:
    description: Method of getting the version
    required: true
    type: string

  version-path:
    description: Path to the file containing the version
    required: false
    type: string
    default: ''

  head:
    description: Source branch name
    required: false
    type: string
    default: ${{ github.ref_name }}

  base:
    description: Target branch name
    required: false
    type: string
    default: ${{ github.event.repository.default_branch }}
outputs:
  base:
    description:
    exists: ${{ steps.check.outputs.exists }}

runs:
  uses: 'composite'
  steps:
  - name: Prepare base ref
    id: refs
    env:
      GH_TOKEN: ${{ github.token }}
    shell: bash
    run: |
      BASE_NAME="${{ inputs.base }}"
      HEAD_NAME="${{ inputs.head }}"

      if [ $(gh pr list \
              --repo "$GITHUB_REPOSITORY" \
              --head "$HEAD_NAME" \
              --base "$BASE_NAME" \
              --json title \
              --jq "length") != 0 ]; then
        echo "true" >> "$GITHUB_OUTPUT"
      fi
