name: Merge
run-name: Merging ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}

on:
  workflow_call:
    inputs:


jobs:
  merge:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Merge
      env:
        GH_TOKEN: ${{ github.token }}
        BODY: ${{ github.event.pull_request.body }}
      shell: bash
      run: |
        gh pr merge \
          ${{ github.event.pull_request.number }} \
          --repo "$GITHUB_REPOSITORY" \
          --subject "${{ github.event.pull_request.title }}" \
          --body "$BODY" \
          --auto \
          ${{ github.event.pull_request.base.ref
              == github.event.repository.default_branch
              && '--squash' || '--merge'}} \
          ${{ github.event.pull_request.base.ref
              != github.event.repository.default_branch
              && github.event.pull_request.base.ref
              != 'release-candidate'
              && '--delete-branch \' || '' }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          action.yaml
          ${{ github.event.pull_request.base.ref
              != github.event.repository.default_branch
              && 'version.txt
                  .github/actions/pr-create/action.yaml'
              || '' }}
        sparse-checkout-cone-mode: false
    - name: Create PR
      if: github.event.pull_request.base.ref
          != github.event.repository.default_branch
      uses: ./.github/actions/pr-create
      with:
        version-from: 'version-file'
        head: ${{ github.event.pull_request.base.ref }}
    - name: Count matching paths
      if: github.event.pull_request.base.ref
          == github.event.repository.default_branch
      id: paths
      env:
        PATTERN: '(action.yaml)|(version.txt)|(README.md)'
      run: |
        printf "matches=%$( \
          git diff --name-only \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }} \
          | grep -c $PATTERN ).s" \
        | tr ' ' 'x' \
        >> "$GITHUB_OUTPUT"
  release:
    needs:
    - merge
    if: github.event.pull_request.base.ref
        == github.event.repository.default_branch
        && github.event.review.state == 'approved'
    uses: ${{ inputs.release-hook }}
    with:
      release-hook: ./.github/workflows/release.yaml
