name: Merge
run-name: Merging ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}

on:
  pull_request_review:
    types:
    - submitted

jobs:
  merge:
    if: ${{ github.event.review.state == 'approved' }}
    uses: ./.github/workflows/merge.yaml
    with:
      release-hook: ./.github/workflows/release.yaml
