name: Create PR
run-name: Creating PR from ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      head:
        description: 'Head reference from which the PR is created'
        required: False
        default: ${{ github.ref_name }}

jobs:
  create-pr:
    if: inputs.head != github.event.repository.default_branch
    runs-on: ubuntu-latest
    permissions:
       pull-requests: write
       contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          version.txt
          .github/actions/pr-create/actions.yaml
        sparse-checkout-cone-mode: false
    - name: Create PR
      uses: ./.github/actions/pr-create
      with:
        version-from: 'version-file'
        version-source: 'version.txt'
