name: Create PR
run-name: Creating PR from ${{ github.ref_name }}

on:
  push:

jobs:
  create-pr:
    if: github.ref_name != github.event.repository.default_branch
    permissions:
       pull-requests: write
       contents: read
    uses: ./.github/workflows/pr-create.yaml
