name: Release
run-name: Creating release
on:
  pull_request:
    types:
    - closed
    paths:
    - 'action.yaml'
    - 'version.txt'
    - 'README.md'

jobs:
  release:
    if: github.event.pull_request.base.ref
        == github.event.repository.default_branch
        && github.event.pull_request.merged
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: ''
        sparse-checkout-cone-mode: false
    - name: Release
      uses: ./
