name: Release
description: Creates tag and release based on the commit message
on:
  pull_request:
    types:
    - closed
    paths:
    - 'action.yaml'
    - 'version.txt'
    - 'README.md'

jobs:
  release:
    if: github.event.pull_request.base.ref
        == github.event.repository.default_branch
        && github.event.pull_request.merged
    premissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Release
      uses: ./
