name: Tests
run-name: Testing the action
on:
  push:
    paths:
    - 'action.yaml'
    - '.github/workflows/tests.yaml'
    - 'tests/*'
    - '.github/actions/reset-tags/action.yaml'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        sparse-checkout: |
          action.yaml
          test
          tests/version.txt
          .github/actions/reset-tags/action.yaml
        sparse-checkout-cone-mode: false
    - name: Test commit
      run: |
        touch test
        git config user.email 'github-actions@users.noreply.github.com'
        git config user.name 'GitHub Actions'
        git add test
        git commit -m 'v1.2.alpha.ö'
    - name: Release from commit
      id: release-from-commit
      uses: ./
      with:
        version-from: 'commit-message'
        dry-run: true
    - name: Check
      run: |
        if [ '${{ steps.release-from-commit.outputs.tag }}' != 'v1.2.alpha.ö' ]; then exit 101
        elif ! git rev-parse 'v1.2.alpha.ö' >/dev/null 2>&1; then exit 102
        elif ! git rev-parse 'v1.2.alpha' >/dev/null 2>&1; then exit 103
        elif ! git rev-parse 'v1.2' >/dev/null 2>&1; then exit 104
        elif ! git rev-parse 'latest' >/dev/null 2>&1; then exit 105
        fi
    - name: Reset tags
      uses: ./.github/actions/reset-tags
    - name: Release candidate
      uses: ./
      with:
        version-from: 'version-file'
        version-source: 'tests/version_1.2.alpha.ö.txt'
        release-candidate: true
        dry-run: true
    - name: Check
      run: |
        if ! git rev-parse 'v1.2.alpha.ö.rc1' >/dev/null 2>&1; then
          exit 101
        elif ! git rev-parse 'latest-rc' >/dev/null 2>&1; then
          exit 102
        fi
    - name: Reset tags
      uses: ./.github/actions/reset-tags
    - name: Increment rc
      id: increment
      uses: ./
      with:
        version-from: 'version-file'
        version-source: 'tests/version_0.1.2.txt'
        release-candidate: true
        dry-run: true
    - name: Check
      run: |
        if ! git rev-parse 'v0.1.2.rc2' >/dev/null 2>&1; then
          echo "${{ steps.increment.outputs.tag }}"
          exit 101
        fi
    - name: Reset tags
      uses: ./.github/actions/reset-tags
    - name: Release candidate suffix
      id: release-suffix
      uses: ./
      with:
        version-from: 'version-file'
        version-source: 'tests/version_0.1.2.txt'
        release-candidate: true
        release-candidate-suffix: 'RC'
        dry-run: true
    - name: Fail
      if: steps.release-suffix.outputs.tag != 'v1.2.alpha.ö.RC1'
      run: |
        echo "${{ steps.release-suffix.outputs.tag }}"
        exit 101
